import { sva } from "styled-system/css";

export const articleLayout = sva({
  slots: ["root", "nav", "mobileNav", "content", "topic", "title", "standfirst", "meta", "takeaway", "body"],
  base: {
    root: {
      maxW: "content",
      mx: "auto",
      px: "pageX",
      py: { base: "3rem", md: "sectionY" },
      display: "grid",
      gridTemplateColumns: { base: "1fr", lg: "220px minmax(0, 1fr)" },
      gap: { base: "2rem", lg: "4rem" },
    },
    nav: {
      display: { base: "none", lg: "block" },
      position: "sticky",
      top: "2rem",
      alignSelf: "start",
      borderRight: "hairline solid token(colors.divider)",
      pr: "1rem",
      "& p": { fontWeight: 700, mb: "0.85rem" },
      "& ol": { listStyle: "none", display: "grid", gap: "0.65rem" },
      "& a": { color: "rgba(36, 43, 39, 0.7)", textDecoration: "none", fontSize: "0.95rem" },
      "& a:hover": { color: "accent" },
    },
    mobileNav: {
      display: { base: "block", lg: "none" },
      border: "hairline solid token(colors.divider)",
      borderRadius: "card",
      p: "1rem",
      mb: "2rem",
      "& summary": { cursor: "pointer", fontWeight: 700 },
      "& ol": { mt: "1rem", pl: "1.25rem" },
      "& li + li": { mt: "0.5rem" },
    },
    content: { minW: 0, maxW: "reading" },
    topic: { color: "accent", fontWeight: 700, mb: "1rem" },
    title: {
      fontSize: { base: "2.5rem", md: "4rem" },
      lineHeight: "tight",
      letterSpacing: "-0.06em",
      mb: "1rem",
    },
    standfirst: { fontSize: "lead", lineHeight: "body", color: "rgba(36, 43, 39, 0.78)", mb: "1rem" },
    meta: { color: "rgba(36, 43, 39, 0.66)", fontSize: "0.95rem", mb: "2rem" },
    takeaway: {
      bg: "note",
      border: "hairline solid token(colors.divider)",
      borderRadius: "card",
      p: "1rem",
      mb: "2.5rem",
      lineHeight: "body",
    },
    body: {
      "& section + section": { mt: "3rem" },
      "& h2": { fontSize: { base: "1.8rem", md: "2.3rem" }, letterSpacing: "-0.04em", mb: "1rem" },
      "& p": { color: "rgba(36, 43, 39, 0.82)", fontSize: "body", lineHeight: "body", mb: "1rem" },
      "& ul": { pl: "1.25rem", mb: "1rem" },
      "& li": { lineHeight: "body", color: "rgba(36, 43, 39, 0.82)" },
      "& li + li": { mt: "0.5rem" },
      "& table": { display: "block", overflowX: "auto", borderCollapse: "collapse", my: "1.5rem", fontSize: "0.95rem" },
      "& th, & td": { border: "hairline solid token(colors.divider)", p: "0.75rem", textAlign: "left", verticalAlign: "top" },
      "& th": { bg: "note" },
      "& pre": { overflowX: "auto", bg: "#242B27", color: "#F7F8F5", p: "1rem", borderRadius: "card", my: "1.5rem", fontSize: "0.92rem" },
      "& code": { fontFamily: "monospace" },
    },
  },
});
